const data = [
   {
      id:1 ,
      image:'ecommerce',
      title:'E-Commerce' ,
      category: 'Mi Trabajo',
      github: 'https://github.com/Mardelys/Gustosos-Ovejitos',
      link: 'https://gustotos-ovejitos.vercel.app',
      description:'Es una aplicación para venta de comida rápida, donde el usuario puede ver el menú por categorias, seleccionar  su pedido y verlo en el carrito,al finalizar se envía un mensaje vía whatsapp con el pedido',
   },
   {
      id:2 ,
      image:'portfolio',
      title:'Portafolio' ,
      category: 'Mi Trabajo',
      github: 'https://github.com/Mardelys/Protfolio-Web',
      link: 'https://protfolio-mardelys-torres.vercel.app/',
      description:'Este proyecto fue creado para darme a conocer como desarrollador y diseñador de aplicaciones web, creando mi presentación y proyectos.',
   },
   {
      id:3 ,
      image:'crud',
      title:'CRUD Peliculas' ,
      category: 'Colaboraciones',
      github: 'https://github.com/ElPardo16/video_club',
      link: 'https://video-club-grupo3.netlify.app/',
      description:'Este proyecto se desarrolló en equipo utilizando next js para hacer el crud, se pueden agregar, modificar y eliminar películas. ',
   },
   {
      id:4 ,
      image:'crudtodo',
      title:'CRUD To-do List' ,
      category: 'Colaboraciones',
      github: 'https://github.com/ElPardo16/to-do-grupo3',
      link: 'https://to-do-grupo3.netlify.app/',
      description:'Con este proyecto se puede agregar, editar y eliminar tareas, además puede observar las tareas eliminadas y las que estan hechas ',
   },
   {
      id:5 ,
      image:'game',
      title:'Weel of Doom - game' ,
      category: 'Colaboraciones',
      js:'obj.style1',
      react:'obj.style',
      github: 'https://github.com/ElPardo16/wheel-of-doom-g5/tree/main',
      link: 'https://wheel-of-doom-g5.netlify.app/',
      description:'El juego es desarrollado en el contexto de un proyecto real, donde el cliente desea un juego de sorteo de personas con temática de halloween, el reto fue desarrollar animaciones con css, javascript y Gsap.',
   },
   {
      id:6 ,
      image:'tetris',
      title:'Juego Tetris' ,
      category: 'Colaboraciones',
      js:'obj.style1',
      react:'obj.style',
      github: 'https://github.com/Mardelys/Tetris-Javascript',
      link: 'https://tetris-zm51.vercel.app/',
      description:'Nada como los clásicos, y por que nó aprender la logica de estos juegos de antaño, definitivamente un gran reto pero excelente experiencia que dejó muchos conocimientos, ¡Disfrutalo!',
   },
   {
      id:7 ,
      image:'calculator',
      title:'Calculadora en JS' ,
      category: 'Mi Trabajo',
      js:'obj.style1',
      react:'obj.style',
      github: 'https://github.com/Mardelys/Calculadora-JS',
      link: 'https://calculator-mardelys.netlify.app/',
      description:'Explorando las maravillas de jacvascript, este proyecto consiste en una calculadora, capáz de realizar operaciones básicas como suma, resta, multiplicación y división',
   },
   {
      id:8 ,
      image:'todo',
      title:'Lista de tareas TO-DO' ,
      category: 'Mi Trabajo',
      js:'obj.style1',
      react:'obj.style',
      github: 'https://github.com/Mardelys/to-do-list-app',
      link: 'https://to-do-list-mardelys.netlify.app/',
      description:'Nada como tener tu propia aplicación para tus tareas, y mejor aún desarrollarla tu mismo, esta aplicación permite añadir tareas y contiene un checkbox animado.',
   },
   {
      id:9 ,
      image:'bitcoins',
      title:'Dashboard cripto- API ' ,
      category: 'Mi Trabajo',
      js:'obj.style1',
      react:'obj.style',
      github: 'https://github.com/Mardelys/Dashboard-Cripto',
      link: 'https://mardelys-dashboard-cripto.netlify.app/',
      description:'Este desarrollo consume una api de criptomonedas y las refleja mediante tablas y gráficas, tambien posée un converson de moneda.',
   },
   {
      id:10 ,
      image:'sabujcha',
      title:'Sabujcha Té' ,
      category: 'Mi Trabajo',
      js:'obj.style1',
      react:'obj.style',
      github: 'https://github.com/Mardelys/SabujCha',
      link: 'https://sabujcha-mardelys.netlify.app/',
      description:'Esta landing page se desarrolló con la guía de las fotos de un mockups, y el reto fue lograr que quedara lo mas parecida posible,se suministraron tipos de fuente e imágenes.',
   },
   {
      id:11 ,
      image:'semillas',
      title:' Fundación semillas ' ,
      category: 'Colaboraciones',
      js:'obj.style1',
      react:'obj.style',
      github: 'https://github.com/ElPardo16/Fundacion-semillas-css',
      link: 'https://semillas-css.netlify.app/',
      description:'Este proyecto es desarrollado en un contexto específico, un profesor que inicia sesión a un dashboard que le permite llevar el seguimiento de cada estudiante.',
   },
   {
      id:12 ,
      image:'deezer',
      title:'Diseñando para deezer ' ,
      category: 'Colaboraciones',
      js:'obj.style1',
      react:'obj.style',
      github: 'https://github.com/FelipeSoftlu/Deezer-Tributo/tree/main',
      link: 'https://felipesoftlu.github.io/Deezer-Tributo/',
      description:'Este proyecto se desarrollo en colaboración, se créa una replica de ña página principal de  deezer, el reto fue determinar se es capáz de replicar este tipo de páginas y sin recursos.',
   },
   
]
export default data;