const data = [
   {
      id:1 ,
      image:'ecommerce',
      title:'E-Commerce' ,
      category: 'My Work',
      github: 'https://github.com/Mardelys/Gustosos-Ovejitos',
      link: 'https://gustotos-ovejitos.vercel.app',
      description:'Lotryu bbuninhbbvbjshdflshlighsdlkfhsdfsbcjadbsaj',
   },
   {
      id:2 ,
      image:'game',
      title:'Weel of Doom' ,
      category: 'Collaborations',
      js:'obj.style1',
      react:'obj.style',
      github: 'www.https://github.com/Mardelys/Gustosos-Ovejitos',
      link: 'www.https://gustotos-ovejitos.vercel.app/',
      description:'klshdasjlfhlashlfasbfbas',
   },
   {
      id:3 ,
      image:'game',
      title:'Weel of Doom' ,
      category: 'Collaborations',
      js:'obj.style1',
      react:'obj.style',
      github: 'www.https://github.com/Mardelys/Gustosos-Ovejitos',
      link: 'www.https://gustotos-ovejitos.vercel.app/',
      description:'klshdasjlfhlashlfasbfbas',
   },
   {
      id:4 ,
      image:'game',
      title:'Weel of Doom' ,
      category: 'Collaborations',
      js:'obj.style1',
      react:'obj.style',
      github: 'https://github.com/Mardelys/Gustosos-Ovejitos',
      link: 'https://gustotos-ovejitos.vercel.app/',
      description:'klshdasjlfhlashlfasbfbas',
   },
   {
      id:5 ,
      image:'game',
      title:'Weel of Doom' ,
      category: 'Collaborations',
      js:'obj.style1',
      react:'obj.style',
      github: 'www.https://github.com/Mardelys/Gustosos-Ovejitos',
      link: 'www.https://gustotos-ovejitos.vercel.app/',
      description:'klshdasjlfhlashlfasbfbas',
   },
   {
      id:6 ,
      image:'game',
      title:'Weel of Doom' ,
      category: 'Collaborations',
      js:'obj.style1',
      react:'obj.style',
      github: 'www.https://github.com/Mardelys/Gustosos-Ovejitos',
      link: 'www.https://gustotos-ovejitos.vercel.app/',
      description:'klshdasjlfhlashlfasbfbas',
   },
   
]
export default data;